# Copyright (c) 2021, WSO2 Inc. (http://www.wso2.org) All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

wso2:
  subscription:
    username: ""
    password: ""

  choreoAnalytics:
    enabled: false
    endpoint: ""
    onpremKey: ""

  deployment:
    dependencies:
      cluster_mysql: true
      nfsServerProvisioner: true

    persistentRuntimeArtifacts:
      storageClass: &storage_class "nfs"
      apacheSolrIndexing:
        enabled: false
        capacity:
          carbonDatabase: 50M
          solrIndexedData: 50M

    am:
      dockerRegistry: "docker.wso2.com"
      imageName: "wso2am"
      imageTag: "4.2.0.0"
      imagePullPolicy: Always

      nodeSelector: {}
      affinity: {}
      tolerations: []
      resources:
        requests:
          memory: "1Gi"
          cpu: "1000m"
        limits:
          memory: "2Gi"
          cpu: "2000m"
        jvm:
          heap:
            memory:
              xms: "512m"
              xmx: "512m"

      startupProbe:
        initialDelaySeconds: 45
        periodSeconds: 5
        failureThreshold: 8
      livenessProbe:
        periodSeconds: 10
      readinessProbe:
        initialDelaySeconds: 50
        periodSeconds: 10

      websub:
        ingress:
          enabled: true
          className: ""
          hostname: "websub.am.wso2.com"
          annotations:
            kubernetes.io/ingress.class: "nginx"
            nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"

      websocket:
        ingress:
          enabled: true
          className: ""
          hostname: "websocket.am.wso2.com"
          annotations:
            kubernetes.io/ingress.class: "nginx"
            nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"

      gateway:
        ingress:
          enabled: true
          className: ""
          hostname: "gateway.am.wso2.com"
          annotations:
            kubernetes.io/ingress.class: "nginx"
            nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"

        replicas: 2
        strategy:
          rollingUpdate:
            maxSurge: 2
            maxUnavailable: 0

        # Scheduling controls for the Gateway deployment (independent of other AM components)
        nodeSelector: {}
        affinity: {}
        tolerations: []

        # config:
        #   deployment.toml: |-
        #     # deployment configurations for the Gateway profile of WSO2 API Manager v4.0.0

      trafficmanager:
        livenessProbe:
          initialDelaySeconds: 180
          periodSeconds: 10
        readinessProbe:
          initialDelaySeconds: 180
          periodSeconds: 10
        resources:
          requests:
            memory: "2Gi"
            cpu: "2000m"
          limits:
            memory: "3Gi"
            cpu: "3000m"
          jvm:
            heap:
              memory:
                xms: "1024m"
                xmx: "1024m"

        # config:
        #   deployment.toml: |-
        #     # deployment configurations for the Gateway profile of WSO2 API Manager v4.0.0

      cp:
        db:
          hostname: wso2am-mysql-db-service
          port: 3306
          type: mysql
          driver: com.mysql.cj.jdbc.Driver
          driver_url: https://repo1.maven.org/maven2/mysql/mysql-connector-java/8.0.29/mysql-connector-java-8.0.29.jar
          apim:
            username: wso2carbon
            password: wso2carbon
            url: jdbc:mysql://wso2am-mysql-db-service:3306/WSO2AM_DB?useSSL=false&amp;autoReconnect=true&amp;requireSSL=false&amp;verifyServerCertificate=false
          apim_shared:
            username: wso2carbon
            password: wso2carbon
            url: jdbc:mysql://wso2am-mysql-db-service:3306/WSO2AM_SHARED_DB?useSSL=false&amp;autoReconnect=true&amp;requireSSL=false&amp;verifyServerCertificate=false
        startupProbe:
          initialDelaySeconds: 60
          periodSeconds: 5
          failureThreshold: 8
        livenessProbe:
          periodSeconds: 10
        readinessProbe:
          initialDelaySeconds: 80
          periodSeconds: 10

        ingress:
          enabled: true
          className: ""
          hostname: "am.wso2.com"
          annotations:
            kubernetes.io/ingress.class: "nginx"
            nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
            nginx.ingress.kubernetes.io/affinity: "cookie"
            nginx.ingress.kubernetes.io/session-cookie-name: "route"
            nginx.ingress.kubernetes.io/session-cookie-hash: "sha1"

        resources:
          requests:
            memory: "2Gi"
            cpu: "2000m"
          limits:
            memory: "3Gi"
            cpu: "3000m"
          jvm:
            heap:
              memory:
                xms: "1024m"
                xmx: "1024m"

        # config:
        #   deployment.toml: |-
        #     # deployment configurations for the Control Plane profile of WSO2 API Manager v4.0.0

    mi:
      dockerRegistry: "docker.wso2.com"
      imageName: "wso2mi"
      imageTag: "4.2.0.0"
      replicas: 2
      strategy:
        rollingUpdate:
          maxSurge: 1
          maxUnavailable: 0
      nodeSelector: {}
      affinity: {}
      tolerations: []
      startupProbe:
        initialDelaySeconds: 10
        periodSeconds: 5
        failureThreshold: 8
      livenessProbe:
        periodSeconds: 10
      readinessProbe:
        initialDelaySeconds: 35
        periodSeconds: 10
      resources:
        requests:
          memory: "512Mi"
          cpu: "500m"
        limits:
          memory: "1Gi"
          cpu: "1000m"
      envs:
      #  ENV_NAME: ENV_VALUE

      # config:
      #   deployment.toml: |-
      #     # toml configurations for the WSO2 MI v4.2.0

      synapseTest:
        enabled: false

      ingress:
        className: ""
        management:
          hostname: "management.mi.wso2.com"
          annotations:
            kubernetes.io/ingress.class: "nginx"
            nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"

kubernetes:
  serviceAccount: "wso2am-pattern-4-svc-account"

mysql-am:
  mysql:
    persistence:
      storageClass: *storage_class
