[server]
hostname = "$env{HOST_NAME}"
node_ip = "$env{NODE_IP}"
server_role = "gateway-worker"
offset = "0"

[user_store]
type = "database_unique_id"

[super_admin]
username = "admin"
password = "admin"
create_admin_account = true

[database.shared_db]
#type = "h2"
#hostname = "jdbc:h2:./repository/database/WSO2SHARED_DB;DB_CLOSE_ON_EXIT=FALSE"
#username = "wso2carbon"
#password = "wso2carbon"
type = "mysql"
url = "jdbc:mysql://wso2am-mysql-db-service:3306/WSO2AM_SHARED_DB?useSSL=false&amp;autoReconnect=true&amp;requireSSL=false&amp;verifyServerCertificate=false"
username = "wso2carbon"
password = "wso2carbon"
driver = "com.mysql.cj.jdbc.Driver"

[keystore.tls]
file_name =  "wso2carbon.jks"
type =  "JKS"
password =  "wso2carbon"
alias =  "wso2carbon"
key_password =  "wso2carbon"

[truststore]
file_name = "client-truststore.jks"
type = "JKS"
password = "wso2carbon"

# key manager implementation
[apim.key_manager]
service_url = "https://wso2am-pattern-3-km-service:${mgt.transport.https.port}/services/"
username= "$ref{super_admin.username}"
password= "$ref{super_admin.password}"
#pool.init_idle_capacity=50
#pool.max_idle=100
#custom_key_validation_handler="org.wso2.carbon.apimgt.keymgt.handlers.DefaultKeyValidationHandler"

# Traffic Manager configurations
[apim.throttling]
username= "$ref{super_admin.username}"
password= "$ref{super_admin.password}"

enable_unlimited_tier = true
enable_header_based_throttling = false
enable_jwt_claim_based_throttling = false
enable_query_param_based_throttling = false

throttle_decision_endpoints = ["tcp://wso2am-pattern-3-am-tm-1-service:5672", "tcp://wso2am-pattern-3-am-tm-2-service:5672"]

[[apim.throttling.url_group]]
traffic_manager_urls = ["tcp://wso2am-pattern-3-am-tm-1-service:9611"]
traffic_manager_auth_urls = ["ssl://wso2am-pattern-3-am-tm-1-service:9711"]
type = "loadbalance"

[[apim.throttling.url_group]]
traffic_manager_urls = ["tcp://wso2am-pattern-3-am-tm-2-service:9611"]
traffic_manager_auth_urls = ["ssl://wso2am-pattern-3-am-tm-2-service:9711"]
type = "loadbalance"

[apim.analytics]
enable = "true"
store_api_url = "https://wso2am-pattern-3-am-analytics-worker-service:7444"
username= "$ref{super_admin.username}"
password= "$ref{super_admin.password}"

[[apim.analytics.url_group]]
analytics_url =["tcp://wso2am-pattern-3-am-analytics-worker-1-service:7612","tcp://wso2am-pattern-3-am-analytics-worker-2-service:7612"]
analytics_auth_url =["ssl://wso2am-pattern-3-am-analytics-worker-1-service:7712","ssl://wso2am-pattern-3-am-analytics-worker-2-service:7712"]
type = "failover"

[apim.cache.gateway_token]
enable = true
expiry_time = 15

[apim.cache.resource]
enable = true

[apim.oauth_config]
remove_outbound_auth_header = true
auth_header = "Authorization"

[apim.cors]
allow_origins = "*"
allow_methods = ["GET","PUT","POST","DELETE","PATCH","OPTIONS"]
allow_headers = ["authorization","Access-Control-Allow-Origin","Content-Type","SOAPAction"]
allow_credentials = false

[transport.passthru_https.sender.parameters]
HostnameVerifier = "AllowAll"
