
apiVersion: v1
kind: Service
metadata:
  name: wso2am-pattern-1-analytics-worker-service
  namespace: wso2
spec:
  # label keys and values that must match in order to receive traffic for this service
  selector:
    deployment: wso2am-pattern-1-analytics-worker
    product: api-manager
  ports:
    # ports that this service should serve on
    -
      name: 'thrift'
      port: 7612
      protocol: TCP
    -
      name: 'thrift-ssl'
      port: 7712
      protocol: TCP
    -
      name: 'rest-api-port-1'
      protocol: TCP
      port: 9444
    -
      name: 'rest-api-port-2'
      protocol: TCP
      port: 9091
    -
      name: 'rest-api-port-3'
      protocol: TCP
      port: 7071
    -
      name: 'rest-api-port-4'
      protocol: TCP
      port: 7444
---
