FROM ubuntu:latest
MAINTAINER dev@wso2.org

RUN apt-get update && apt-get -y install cron

# Add crontab file in the cron directory
ADD artifact-sync-cron /etc/cron.d/

# Give execution rights on the cron job
RUN chmod 0644 /etc/cron.d/artifact-sync-cron

# Create the log file to be able to run tail
RUN touch /var/log/cron.log

# Run the command on container startup
CMD cron && tail -f /var/log/cron.log
