# Copyright (c) 2016, WSO2 Inc. (http://www.wso2.org) All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: wso2apim-with-analytics-apim-analytics-deployment
  namespace : {{ .Values.namespace }}
spec:
  replicas: 1
  minReadySeconds: 30
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        deployment: wso2apim-with-analytics-apim-analytics
    spec:
      containers:
      - name: wso2apim-with-analytics-apim-analytics
        {{- if or (eq .Values.username "") (eq .Values.password "") }}
        image: wso2/wso2am-analytics-worker:2.6.0
        {{- else }}
        image: docker.wso2.com/wso2am-analytics-worker:2.6.0
        {{- end }}
        resources:
          limits:
            memory: "4Gi"
          requests:
            memory: "4Gi"
        livenessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - nc -z localhost 7712
          initialDelaySeconds: 250
          periodSeconds: 10
        readinessProbe:
          exec:
            command:
              - /bin/sh
              - -c
              - nc -z localhost 7712
          initialDelaySeconds: 250
          periodSeconds: 10
        lifecycle:
          preStop:
            exec:
              command:  ['sh', '-c', '${WSO2_SERVER_HOME}/bin/worker.sh stop']
        imagePullPolicy: Always
        securityContext:
          runAsUser: 802
        ports:
        -
          containerPort: 9764
          protocol: "TCP"
        -
          containerPort: 9444
          protocol: "TCP"
        -
          containerPort: 7612
          protocol: "TCP"
        -
          containerPort: 7712
          protocol: "TCP"
        -
          containerPort: 9091
          protocol: "TCP"
        -
          containerPort: 7071
          protocol: "TCP"
        -
          containerPort: 7444
          protocol: "TCP"
        volumeMounts:
        - name: apim-analytics-conf-worker
          mountPath: /home/wso2carbon/wso2-config-volume/conf/worker
      serviceAccountName: "wso2svc-account"
      {{ if and (not (eq .Values.username "")) (not (eq .Values.password "")) }}
      imagePullSecrets:
      - name: wso2creds
      {{ end }}
      volumes:
      - name: apim-analytics-conf-worker
        configMap:
          name: apim-analytics-conf-worker
