apiVersion: v1
kind: Service
metadata:
  name: wso2apim-with-analytics-apim-analytics-service
  namespace: "$ns.k8s.&.wso2.apim"
spec:
  selector:
    deployment: wso2apim-with-analytics-apim-analytics
  ports:
    -
      name: 'thrift'
      port: 7612
      protocol: TCP
    -
      name: 'thrift-ssl'
      port: 7712
      protocol: TCP
    -
      name: 'rest-api-port-1'
      protocol: TCP
      port: 9444
    -
      name: 'rest-api-port-2'
      protocol: TCP
      port: 9091
    -
      name: 'rest-api-port-3'
      protocol: TCP
      port: 7071
    -
      name: 'rest-api-port-4'
      protocol: TCP
      port: 7444
---
