# Copyright (c) 2018, WSO2 Inc. (http://www.wso2.org) All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "am-pattern-1.resource.prefix" . }}-am-conf
  namespace : {{ .Release.Namespace }}
  {{ if .Values.wso2.deployment.am.config }}
data:
  {{- range $index, $content := .Values.wso2.deployment.am.config }}
  {{ $index }}: |-
    {{ tpl $content $ | indent 4 }}
  {{- end }}

  {{ else }}
data:
  deployment.toml: |-
    [server]
    hostname = "{{ .Values.wso2.deployment.am.hostname }}"
    node_ip = "$env{NODE_IP}"
    #offset=0
    mode = "single" #single or ha
    base_path = "${carbon.protocol}://${carbon.host}:${carbon.management.port}"
    #discard_empty_caches = false
    server_role = "default"

    [super_admin]
    username = "admin"
    password = "admin"
    create_admin_account = true

    [user_store]
    type = "database_unique_id"

    [database.apim_db]
    type = "mysql"
    url = "jdbc:mysql://wso2am-mysql-db-service:3306/WSO2AM_DB?autoReconnect=true&amp;useSSL=false"
    username = "wso2carbon"
    password = "wso2carbon"
    driver = "com.mysql.cj.jdbc.Driver"

    [database.shared_db]
    type = "mysql"
    url = "jdbc:mysql://wso2am-mysql-db-service:3306/WSO2AM_SHARED_DB?autoReconnect=true&amp;useSSL=false"
    username = "wso2carbon"
    password = "wso2carbon"
    driver = "com.mysql.cj.jdbc.Driver"

    [keystore.tls]
    file_name =  "wso2carbon.jks"
    type =  "JKS"
    password =  "wso2carbon"
    alias =  "wso2carbon"
    key_password =  "wso2carbon"

    [[apim.gateway.environment]]
    name = "Production and Sandbox"
    type = "hybrid"
    display_in_api_console = true
    description = "This is a hybrid gateway that handles both production and sandbox token traffic."
    show_as_token_endpoint_url = true
    service_url = "https://localhost:${mgt.transport.https.port}/services/"
    username= "${admin.username}"
    password= "${admin.password}"
    ws_endpoint = "ws://localhost:9099"
    wss_endpoint = "wss://localhost:8099"
    http_endpoint = "http://{{ .Values.wso2.deployment.am.gateway.hostname }}"
    https_endpoint = "https://{{ .Values.wso2.deployment.am.gateway.hostname }}"

    [apim.analytics]
    enable = true
    store_api_url = "https://{{ template "am-pattern-1.resource.prefix" . }}-analytics-worker-service:7444"

    [[apim.analytics.url_group]]
    analytics_url =["tcp://{{ template "am-pattern-1.resource.prefix" . }}-am-analytics-worker-statefulset-0.{{ template "am-pattern-1.resource.prefix" . }}-am-analytics-worker-headless-service.{{ .Release.Namespace }}.svc.cluster.local:7612","tcp://{{ template "am-pattern-1.resource.prefix" . }}-am-analytics-worker-statefulset-1.{{ template "am-pattern-1.resource.prefix" . }}-am-analytics-worker-headless-service.{{ .Release.Namespace }}.svc.cluster.local:7612"]
    analytics_auth_url =["ssl://{{ template "am-pattern-1.resource.prefix" . }}-am-analytics-worker-statefulset-0.{{ template "am-pattern-1.resource.prefix" . }}-am-analytics-worker-headless-service.{{ .Release.Namespace }}.svc.cluster.local:7712","ssl://{{ template "am-pattern-1.resource.prefix" . }}-am-analytics-worker-statefulset-1.{{ template "am-pattern-1.resource.prefix" . }}-am-analytics-worker-headless-service.{{ .Release.Namespace }}.svc.cluster.local:7712"]
    type = "failover"

    [apim.devportal]
    url = "https://{{ .Values.wso2.deployment.am.hostname }}/devportal"

    [transport.https.properties]
    proxyPort = 443

    [apim.cors]
    allow_origins = "*"
    allow_methods = ["GET","PUT","POST","DELETE","PATCH","OPTIONS"]
    allow_headers = ["authorization","Access-Control-Allow-Origin","Content-Type","SOAPAction"]
    allow_credentials = false

    [apim.throttling]
    enable_data_publishing = true
    #enable_policy_deploy = true
    enable_blacklist_condition = false

    [[apim.throttling.url_group]]
    traffic_manager_urls = ["tcp://{{ template "am-pattern-1.resource.prefix" . }}-am-statefulset-0.{{ template "am-pattern-1.resource.prefix" . }}-am-headless-service.{{ .Release.Namespace }}.svc.cluster.local:9611"]
    traffic_manager_auth_urls = ["ssl://{{ template "am-pattern-1.resource.prefix" . }}-am-statefulset-0.{{ template "am-pattern-1.resource.prefix" . }}-am-headless-service.{{ .Release.Namespace }}.svc.cluster.local:9711"]
    type = "loadbalance"

    [[apim.throttling.url_group]]
    traffic_manager_urls = ["tcp://{{ template "am-pattern-1.resource.prefix" . }}-am-statefulset-1.{{ template "am-pattern-1.resource.prefix" . }}-am-headless-service.{{ .Release.Namespace }}.svc.cluster.local:9611"]
    traffic_manager_auth_urls = ["ssl://{{ template "am-pattern-1.resource.prefix" . }}-am-statefulset-1.{{ template "am-pattern-1.resource.prefix" . }}-am-headless-service.{{ .Release.Namespace }}.svc.cluster.local:9711"]
    type = "loadbalance"

    [[event_handler]]
    name="userPostSelfRegistration"
    subscriptions=["POST_ADD_USER"]

    [service_provider]
    sp_name_regex = "^[\\sa-zA-Z0-9._-]*$"

    [indexing]
    location = "/home/wso2carbon/solr/indexed-data"
    re_indexing = "$env{SOLR_INDEX_INSTANCE_ID}"
  {{- end }}
