# Copyright (c) 2021, WSO2 Inc. (http://www.wso2.org) All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "am-pattern-4.resource.prefix" . }}-am-gateway-conf
  namespace : {{ .Release.Namespace }}
  {{ if .Values.wso2.deployment.am.gateway.config }}
data:
  {{- range $index, $content := .Values.wso2.deployment.am.gateway.config }}
  {{ $index }}: |-
  {{ tpl $content $ | indent 4 }}
  {{- end }}

  {{ else }}
data:
  deployment.toml: |-
    [server]
    hostname = "{{ .Values.wso2.deployment.am.gateway.ingress.hostname }}"
    node_ip = "$env{NODE_IP}"
    server_role = "gateway-worker"

    [user_store]
    type = "database_unique_id"

    [super_admin]
    username = "admin"
    password = "admin"
    create_admin_account = true

    [database.shared_db]
    type = "h2"
    url = "jdbc:h2:./repository/database/WSO2SHARED_DB;DB_CLOSE_ON_EXIT=FALSE"
    username = "wso2carbon"
    password = "wso2carbon"

    [keystore.tls]
    file_name =  "wso2carbon.jks"
    type =  "JKS"
    password =  "wso2carbon"
    alias =  "wso2carbon"
    key_password =  "wso2carbon"

    [truststore]
    file_name = "client-truststore.jks"
    type = "JKS"
    password = "wso2carbon"

    # key manager implementation
    [apim.key_manager]
    service_url = "https://{{ template "am-pattern-4.resource.prefix" . }}-am-cp-service:${mgt.transport.https.port}/services/"
    username= "$ref{super_admin.username}"
    password= "$ref{super_admin.password}"

    # Event Listener configurations
    [[event_listener]]
    id = "token_revocation"
    type = "org.wso2.carbon.identity.core.handler.AbstractIdentityHandler"
    name = "org.wso2.is.notification.ApimOauthEventInterceptor"
    order = 1

    [event_listener.properties]
    notification_endpoint = "https://{{ template "am-pattern-4.resource.prefix" . }}-am-cp-service:${mgt.transport.https.port}/internal/data/v1/notify"
    username = "${admin.username}"
    password = "${admin.password}"
    'header.X-WSO2-KEY-MANAGER' = "default"

    [apim.event_hub]
    enable = true
    username = "$ref{super_admin.username}"
    password = "$ref{super_admin.password}"
    service_url = "https://{{ template "am-pattern-4.resource.prefix" . }}-am-cp-service:${mgt.transport.https.port}/services/"
    event_listening_endpoints = ["tcp://{{ template "am-pattern-4.resource.prefix" . }}-am-cp-1-service:5672","tcp://{{ template "am-pattern-4.resource.prefix" . }}-am-cp-2-service:5672"]

    [[apim.event_hub.publish.url_group]]
    urls = ["tcp://{{ template "am-pattern-4.resource.prefix" . }}-am-cp-1-service:9611"]
    auth_urls = ["ssl://{{ template "am-pattern-4.resource.prefix" . }}-am-cp-1-service:9711"]

    [[apim.event_hub.publish.url_group]]
    urls = ["tcp://{{ template "am-pattern-4.resource.prefix" . }}-am-cp-2-service:9611"]
    auth_urls = ["ssl://{{ template "am-pattern-4.resource.prefix" . }}-am-cp-2-service:9711"]

    # JWT Generation
    [apim.jwt]
    enable = true
    encoding = "base64" # base64,base64url
    #generator_impl = "org.wso2.carbon.apimgt.keymgt.token.JWTGenerator"
    claim_dialect = "http://wso2.org/claims"
    header = "X-JWT-Assertion"
    signing_algorithm = "SHA256withRSA"
    #enable_user_claims = true
    #claims_extractor_impl = "org.wso2.carbon.apimgt.impl.token.DefaultClaimsRetriever"

    [apim.sync_runtime_artifacts.gateway]
    gateway_labels =["Default"]

    # Traffic Manager configurations
    [apim.throttling]
    username= "$ref{super_admin.username}"
    password= "$ref{super_admin.password}"
    service_url = "https://{{ template "am-pattern-4.resource.prefix" . }}-am-trafficmanager-service:${mgt.transport.https.port}/services/"
    throttle_decision_endpoints = ["tcp://{{ template "am-pattern-4.resource.prefix" . }}-am-trafficmanager-1-service:5672","tcp://{{ template "am-pattern-4.resource.prefix" . }}-am-trafficmanager-2-service:5672"]
    enable_unlimited_tier = true
    enable_header_based_throttling = false
    enable_jwt_claim_based_throttling = false
    enable_query_param_based_throttling = false

    [[apim.throttling.url_group]]
    traffic_manager_urls = ["tcp://{{ template "am-pattern-4.resource.prefix" . }}-am-trafficmanager-1-service:9611"]
    traffic_manager_auth_urls = ["ssl://{{ template "am-pattern-4.resource.prefix" . }}-am-trafficmanager-1-service:9711"]
    type = "loadbalance"

    [[apim.throttling.url_group]]
    traffic_manager_urls = ["tcp://{{ template "am-pattern-4.resource.prefix" . }}-am-trafficmanager-2-service:9611"]
    traffic_manager_auth_urls = ["ssl://{{ template "am-pattern-4.resource.prefix" . }}-am-trafficmanager-2-service:9711"]
    type = "loadbalance"

    {{ if .Values.wso2.choreoAnalytics.enabled }}
    [apim.analytics]
    enable = true
    config_endpoint = "{{ .Values.wso2.choreoAnalytics.endpoint }}"
    auth_token = "{{ .Values.wso2.choreoAnalytics.onpremKey }}"
    {{ else }}
    [apim.analytics]
    enable = false
    config_endpoint = "https://analytics-event-auth.choreo.dev/auth/v1"
    auth_token = ""
    {{ end }}

    # Caches
    [apim.cache.gateway_token]
    enable = true
    expiry_time = 15

    [apim.cache.resource]
    enable = true

    [apim.cache.jwt_claim]
    enable = true
    expiry_time = 900

    [apim.oauth_config]
    remove_outbound_auth_header = true
    auth_header = "Authorization"

    [apim.cors]
    allow_origins = "*"
    allow_methods = ["GET","PUT","POST","DELETE","PATCH","OPTIONS"]
    allow_headers = ["authorization","Access-Control-Allow-Origin","Content-Type","SOAPAction"]
    allow_credentials = false

    [transport.https.properties]
    port = 9443
    proxyPort = 443

    [transport.passthru_https.sender.parameters]
    HostnameVerifier = "AllowAll"

  {{- end }}
