FROM wso2/wso2am-analytics:2.1.0

COPY carbon/ /home/wso2user/wso2am-analytics-2.1.0/
COPY artifacts/mysql-connector-java-5.1.34-bin.jar \
	/home/wso2user/wso2am-analytics-2.1.0/repository/components/lib/
