# Copyright (c) 2017, WSO2 Inc. (http://www.wso2.org) All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: v1
kind: Service
metadata:
  name: wso2apim-with-analytics-apim-analytics-service
  namespace : {{ .Values.namespace }}
spec:
  # label keys and values that must match in order to receive traffic for this service
  selector:
    deployment: wso2apim-with-analytics-apim-analytics
  ports:
    # ports that this service should serve on
    -
      name: servlet-http
      protocol: TCP
      port: 9764
    -
      name: servlet-https
      protocol: TCP
      port: 9444
    -
      name: thrift
      port: 7612
      protocol: TCP
    -
      name: thrift-ssl
      port: 7712
      protocol: TCP
    -
      name: spark-port-1
      port: 11225
      protocol: TCP
    -
      name: spark-port-2
      port: 10006
      protocol: TCP
    -
      name: spark-port-3
      port: 11001
      protocol: TCP
    -
      name: spark-port-44
      protocol: TCP
      port: 8082
    -
      name: spark-port-5
      protocol: TCP
      port: 4041
    -
      name: spark-port-6
      protocol: TCP
      port: 12001
    -
      name: spark-port-7
      protocol: TCP
      port: 12002
    -
      name: spark-port-8
      protocol: TCP
      port: 12003
    -
      name: spark-port-9
      protocol: TCP
      port: 12004
    -
      name: spark-port-10
      protocol: TCP
      port: 12005
    -
      name: analytics-port-1
      protocol: TCP
      port: 10007
    -
      name: analytics-port-2
      protocol: TCP
      port: 11002
    -
      name: analytics-port-3
      protocol: TCP
      port: 12501
    -
      name: analytics-port-5
      protocol: TCP
      port: 13001
    -
      name: analytics-port-6
      protocol: TCP
      port: 13501
    -
      name: analytics-port-7
      protocol: TCP
      port: 14501
    -
      name: analytics-port-8
      protocol: TCP
      port: 7078
    -
      name: analytics-port-9
      protocol: TCP
      port: 6067
    -
      name: analytics-port-10
      protocol: TCP
      port: 11003
