FROM wso2/rsync:1.0.0

# ARG USER=wso2user
# ARG USER_HOME=/home/wso2user

# copy the artifact-sync-cron with the correct hostname
# COPY artifact-sync-cron ${USER_HOME}/

# USER root 
# RUN chown ${USER} ${USER_HOME}/artifact-sync-cron 
# USER ${USER}

ENV REMOTE_HOST wso2apim-manager-worker
