apiVersion: v1
kind: Service
metadata:
  name: wso2apim-with-analytics-rdbms-service
  namespace: "$ns.k8s.&.wso2.apim"
spec:
  type: ClusterIP
  selector:
    deployment: wso2apim-with-analytics-mysql
  ports:
    - name: mysql-port
      port: 3306
      targetPort: 3306
      protocol: TCP
---
