
apiVersion: v1
kind: Service
metadata:
  name: wso2apim-rdbms-service-mysql
  namespace: wso2
spec:
  type: ClusterIP
  selector:
    deployment: wso2apim-mysql
    product: api-manager
  ports:
    - name: mysql-port
      port: 3306
      targetPort: 3306
      protocol: TCP
---
