# Copyright (c) 2020, WSO2 Inc. (http://www.wso2.org) All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ template "am-pattern-3.resource.prefix" . }}-am-tm-statefulset
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 2
  selector:
    matchLabels:
      deployment: {{ template "am-pattern-3.resource.prefix" . }}-am-tm
  serviceName: {{ template "am-pattern-3.resource.prefix" . }}-am-tm-headless-service
  template:
    metadata:
      annotations:
        checksum.am.tm.conf: {{ include (print $.Template.BasePath "/am/tm/wso2am-pattern-3-am-tm-conf.yaml") . | sha256sum }}
      labels:
        deployment: {{ template "am-pattern-3.resource.prefix" . }}-am-tm
    spec:
      containers:
        - name: wso2am-tm
          {{- if .Values.wso2.deployment.am.dockerRegistry }}
          image: {{ .Values.wso2.deployment.am.dockerRegistry }}/{{ .Values.wso2.deployment.am.imageName }}
          {{- $tag := .Values.wso2.deployment.am.imageTag }}
          {{- if not (eq $tag "") }}{{- printf ":%s" $tag -}}{{- end }}
          {{- else if or (eq .Values.wso2.subscription.username "") (eq .Values.wso2.subscription.password "") }}
          image: wso2/{{ .Values.wso2.deployment.am.imageName }}:{{ .Values.wso2.deployment.am.imageTag }}
          {{- else }}
          image: docker.wso2.com/{{ .Values.wso2.deployment.am.imageName }}:{{ .Values.wso2.deployment.am.imageTag }}
          {{- end }}
          imagePullPolicy: {{ .Values.wso2.deployment.am.imagePullPolicy }}
          env:
            - name: PROFILE_NAME
              value: "traffic-manager"
            - name: NODE_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          livenessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - nc -z localhost 9611
            initialDelaySeconds: {{ .Values.wso2.deployment.am.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.wso2.deployment.am.livenessProbe.periodSeconds }}
          readinessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - nc -z localhost 9611
            initialDelaySeconds: {{ .Values.wso2.deployment.am.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.wso2.deployment.am.readinessProbe.periodSeconds }}
          lifecycle:
            preStop:
              exec:
                command:  ['sh', '-c', '${WSO2_SERVER_HOME}/bin/wso2server.sh stop']
          resources:
            requests:
              memory: {{ .Values.wso2.deployment.am.resources.requests.memory }}
              cpu: {{ .Values.wso2.deployment.am.resources.requests.cpu }}
            limits:
              memory: {{ .Values.wso2.deployment.am.resources.limits.memory }}
              cpu: {{ .Values.wso2.deployment.am.resources.limits.cpu }}
          securityContext:
            runAsUser: 802
          ports:
            - containerPort: 9611
              protocol: TCP
            - containerPort: 9711
              protocol: TCP
            - containerPort: 5672
              protocol: TCP
            - containerPort: 9443
              protocol: TCP
          volumeMounts:
            - name: wso2am-tm-shared-storage-volume
              mountPath: /home/wso2carbon/wso2am-3.1.0/repository/deployment/server/executionplans
            - name: wso2am-tm-conf
              mountPath: /home/wso2carbon/wso2-config-volume/repository/conf
      serviceAccountName: {{ .Values.kubernetes.serviceAccount }}
      {{- if .Values.wso2.deployment.am.imagePullSecrets }}
      imagePullSecrets:
        - name: {{ .Values.wso2.deployment.am.imagePullSecrets }}
      {{- else if and (not (eq .Values.wso2.subscription.username "")) (not (eq .Values.wso2.subscription.password "")) }}
      imagePullSecrets:
        - name: {{ template "am-pattern-3.resource.prefix" . }}-wso2-private-registry-creds
      {{ end }}
      volumes:
        - name: wso2am-tm-shared-storage-volume
          persistentVolumeClaim:
            claimName: {{ template "am-pattern-3.resource.prefix" . }}-am-tm-shared-executionplans-volume-claim
        - name: wso2am-tm-conf
          configMap:
            name: {{ template "am-pattern-3.resource.prefix" . }}-am-tm-conf
