
apiVersion: v1
kind: Service
metadata:
  name: wso2am-pattern-1-am-1-service
  namespace: wso2
spec:
  # label keys and values that must match in order to receive traffic for this service
  selector:
    deployment: wso2am-pattern-1-am
    product: api-manager
  type: NodePort
  ports:
    # ports that this service should serve on
    -
      name: pass-through-http
      protocol: TCP
      # for 8280 with a offset of 22850
      port: 31130
      targetPort: 31130
      nodePort: 30280
    -
      name: pass-through-https
      protocol: TCP
      # for 8243 with a offset of 22850
      port: 31093
      targetPort: 31093
      nodePort: 30243
    -
      name: servlet-http
      protocol: TCP
      # for 9763 with a offset of 22850
      port: 32613
      targetPort: 32613
      nodePort: 30763
    -
      name: servlet-https
      protocol: TCP
      # for 9443 with a offset of 22850
      port: 32293
      targetPort: 32293
      nodePort: 32293
---
