apiVersion: v1
kind: Service
metadata:
  name: wso2apim-with-analytics-apim-service
  namespace: "$ns.k8s.&.wso2.apim"
  labels:
    deployment: wso2apim-with-analytics-apim
spec:
  selector:
    deployment: wso2apim-with-analytics-apim
  type: NodePort
  ports:
    -
      name: pass-through-http
      protocol: TCP
      port: 8280
    -
      name: pass-through-https
      protocol: TCP
      port: 8243
      nodePort: "$nodeport.k8s.&.2.wso2apim"
    -
      name: servlet-http
      protocol: TCP
      port: 9763
    -
      name: servlet-https
      protocol: TCP
      nodePort: "$nodeport.k8s.&.1.wso2apim"
      port: 9443
---
