[server]
hostname = "$env{HOST_NAME}"
node_ip = "$env{NODE_IP}"
server_role = "api-publisher"
offset = "0"

[user_store]
type = "database_unique_id"

[super_admin]
username = "admin"
password = "admin"
create_admin_account = true

[database.apim_db]
type = "mysql"
url = "jdbc:mysql://wso2am-mysql-db-service:3306/WSO2AM_DB?useSSL=false&amp;autoReconnect=true&amp;requireSSL=false&amp;verifyServerCertificate=false"
username = "wso2carbon"
password = "wso2carbon"
driver = "com.mysql.cj.jdbc.Driver"

[database.shared_db]
type = "mysql"
url = "jdbc:mysql://wso2am-mysql-db-service:3306/WSO2AM_SHARED_DB?useSSL=false&amp;autoReconnect=true&amp;requireSSL=false&amp;verifyServerCertificate=false"
username = "wso2carbon"
password = "wso2carbon"
driver = "com.mysql.cj.jdbc.Driver"

[keystore.tls]
file_name =  "wso2carbon.jks"
type =  "JKS"
password =  "wso2carbon"
alias =  "wso2carbon"
key_password =  "wso2carbon"

[truststore]
file_name = "client-truststore.jks"
type = "JKS"
password = "wso2carbon"

[[apim.gateway.environment]]
name= "Production and Sandbox"
type= "hybrid"
display_in_api_console= true
description= "This is a hybrid gateway that handles both production and sandbox token traffic."
service_url= "https://wso2am-pattern-3-am-gateway-service:${mgt.transport.https.port}${carbon.context}services/"
username= "${admin.username}"
password= "${admin.password}"
ws_endpoint = "ws://wso2am-pattern-3-am-gateway-service:9099"
wss_endpoint = "wss://wso2am-pattern-3-am-gateway-service:8099"
http_endpoint = "http://{{ .Release.Name }}-gateway"
https_endpoint = "https://{{ .Release.Name }}-gateway"

[apim.analytics]
enable = "true"
store_api_url = "https://wso2am-pattern-3-am-analytics-worker-service:7444"
username= "$ref{super_admin.username}"
password= "$ref{super_admin.password}"

[[apim.analytics.url_group]]
analytics_url =["tcp://wso2am-pattern-3-am-analytics-worker-1-service:7612","tcp://wso2am-pattern-3-am-analytics-worker-2-service:7612"]
analytics_auth_url =["ssl://wso2am-pattern-3-am-analytics-worker-1-service:7712","ssl://wso2am-pattern-3-am-analytics-worker-2-service:7712"]
type = "failover"

# Traffic Manager configurations
[apim.throttling]
service_url = "https://wso2am-pattern-3-am-tm-service:${mgt.transport.https.port}/services/"
username= "$ref{super_admin.username}"
password= "$ref{super_admin.password}"
throttle_decision_endpoints = ["tcp://wso2am-pattern-3-am-tm-statefulset-0.wso2am-pattern-3-am-tm-headless-service.{{ .Release.Namespace }}.svc.cluster.local:5672","tcp://wso2am-pattern-3-am-tm-statefulset-1.wso2am-pattern-3-am-tm-headless-service.{{ .Release.Namespace }}.svc.cluster.local:5672"]

[[apim.throttling.url_group]]
traffic_manager_urls = ["tcp://wso2am-pattern-3-am-tm-statefulset-0.wso2am-pattern-3-am-tm-headless-service.{{ .Release.Namespace }}.svc.cluster.local:9611"]
traffic_manager_auth_urls = ["ssl://wso2am-pattern-3-am-tm-statefulset-0.wso2am-pattern-3-am-tm-headless-service.{{ .Release.Namespace }}.svc.cluster.local:9711"]
type = "loadbalance"

[[apim.throttling.url_group]]
traffic_manager_urls = ["tcp://wso2am-pattern-3-am-tm-statefulset-1.wso2am-pattern-3-am-tm-headless-service.{{ .Release.Namespace }}.svc.cluster.local:9611"]
traffic_manager_auth_urls = ["ssl://wso2am-pattern-3-am-tm-statefulset-1.wso2am-pattern-3-am-tm-headless-service.{{ .Release.Namespace }}.svc.cluster.local:9711"]
type = "loadbalance"

[apim.cache.scopes]
enable = true

[apim.cache.publisher_roles] #check the usage and move to dev role
enable = true

[apim.devportal]
url = "https://{{ .Release.Name }}-devportal/devportal"

[apim.workflow]
enable = false
service_url = "https://localhost:9445/bpmn"
username = "$ref{super_admin.username}"
password = "$ref{super_admin.password}"
callback_endpoint = "https://localhost:9443/api/am/publisher/v0.16/workflows/update-workflow-status"
token_endpoint = "https://localhost:8243/token"
client_registration_endpoint = "https://localhost:9443/client-registration/v0.16/register"
client_registration_username = "$ref{super_admin.username}"
client_registration_password = "$ref{super_admin.password}"

[transport.https.properties]
proxyPort = 443

[database.local]
url = "jdbc:h2:/home/wso2carbon/solr/database/WSO2CARBON_DB;DB_CLOSE_ON_EXIT=FALSE"

[indexing]
location = "/home/wso2carbon/solr/indexed-data"
