# Copyright (c) 2016, WSO2 Inc. (http://www.wso2.org) All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: v1
kind: PersistentVolume
metadata:
  name: wso2apim-pattern-2-pub-store-tm-executionplans-pv
  labels:
    purpose: wso2apim-pattern-2-pub-store-tm-shared-executionplans
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: <NFS_SERVER_IP>
    path: "<NFS_LOCATION_PATH>"

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: wso2apim-pattern-2-gateway-synapse-configs-pv
  labels:
    purpose: wso2apim-pattern-2-gateway-shared-synapse-configs
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: <NFS_SERVER_IP>
    path: "<NFS_LOCATION_PATH>"

#---
#
#apiVersion: v1
#kind: PersistentVolume
#metadata:
#  name: wso2apim-pattern-2-is-as-km-server-pv
#  labels:
#    purpose: wso2apim-pattern-2-km-shared
#spec:
#  capacity:
#    storage: 1Gi
#  accessModes:
#    - ReadWriteMany
#  persistentVolumeReclaimPolicy: Retain
#  nfs:
#    server: <NFS_SERVER_IP>
#    path: "<NFS_LOCATION_PATH>"
